module.exports =  { 
    GUILD_URL: 'https://www.realmeye.com/guild/',
    PLAYER_URL: 'https://www.realmeye.com/player/',
    USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0 Waterfox/91.3.3',
    PLAYER_DATA: Object.freeze({
		NAME: "name",
		FAME: "fame",
		EXP: "exp",
		STARS: "stars",
		GUILD: "guild",
		GUILDRANK:"guildRank",
		DESC1: "desc1",
		DESC2: "desc2",
		DESC3: "desc3",
	}),
    GUILD_DATA: Object.freeze({
		NAME: "name",
		MEMBERS: "members",
		CHARS: "characters",
		RANK: "rank",
		FAME: "fame",
		EXP: "exp",
		DESC1: "desc1",
		DESC2: "desc2",
		DESC3: "desc3",
	}),
	GUILD_PLAYER_DATA: Object.freeze({
		NAME: "name",
		STARS: "stars",
		GUILDRANK: "guildRank",
		FAME: "fame",
		EXP: "experience",
		CHARS: "characters",
		LASTSEEN: "lastseen",
		SERVER: "server",
		AVGFAME: "averageFame",
		AVGEXP: "averageExp",
	})
};